; Ask for the user's name
MOV A, 87        ; W
MOV B, A
MOV [B], A  ; PUT 87 IN ADDRESS 5
INC B
MOV [B], 10  ; PUT 10 IN ADDRESS 6
INC B
MOV [B], 11  ; PUT 11 IN ADDRESS 7
INC B
MOV [B], 12  ; PUT 12 IN ADDRESS 8
INC B
MOV [B], 7  ; PUT 12 IN ADDRESS 8
INC B
MOV A, [B]  ; PUT 87 IN ADDRESS 5
MOV A, [B]  ; PUT 87 IN ADDRESS 5
HALT
